# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Grid.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(614, 594)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.mMapLayerComboBox = QgsMapLayerComboBox(self.groupBox)
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.horizontalLayout.addWidget(self.mMapLayerComboBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.mFieldComboBox = QgsFieldComboBox(self.groupBox)
        self.mFieldComboBox.setObjectName("mFieldComboBox")
        self.horizontalLayout.addWidget(self.mFieldComboBox)
        self.horizontalLayout.setStretch(1, 8)
        self.horizontalLayout.setStretch(3, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.data_tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.data_tableWidget.setObjectName("data_tableWidget")
        self.data_tableWidget.setColumnCount(0)
        self.data_tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.data_tableWidget)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_surfer_connect_status = QtWidgets.QLabel(Form)
        self.label_surfer_connect_status.setObjectName("label_surfer_connect_status")
        self.verticalLayout.addWidget(self.label_surfer_connect_status)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout.setStretch(5, 4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Call Surfer"))
        self.groupBox.setTitle(_translate("Form", "Data"))
        self.label.setText(_translate("Form", "选择点图层"))
        self.label_2.setText(_translate("Form", "Z 字段"))
        self.groupBox_2.setTitle(_translate("Form", "Preview Data"))
        self.checkBox.setText(_translate("Form", "Surfer Visiable"))
        self.pushButton.setText(_translate("Form", "Load"))
        self.pushButton_2.setText(_translate("Form", "Grid"))
        self.label_surfer_connect_status.setText(_translate("Form", "Status"))
from qgsfieldcombobox import QgsFieldComboBox
from qgsmaplayercombobox import QgsMapLayerComboBox
