# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Grid.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(803, 594)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mFeatureListComboBox = QgsFeatureListComboBox(self.groupBox)
        self.mFeatureListComboBox.setObjectName("mFeatureListComboBox")
        self.verticalLayout_2.addWidget(self.mFeatureListComboBox)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem)
        self.label_surfer_connect_status = QtWidgets.QLabel(Form)
        self.label_surfer_connect_status.setObjectName("label_surfer_connect_status")
        self.verticalLayout.addWidget(self.label_surfer_connect_status)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Data"))
        self.label_surfer_connect_status.setText(_translate("Form", "Status"))


from qgsfeaturelistcombobox import QgsFeatureListComboBox
